export const categoryMappings = {
    "american restaurant, american food, restaurant": "🍔",
    "asian restaurant, asian food, restaurant": "🍚",
    "australian restaurant, australian food, restaurant": "🦘",
    "bar (alcohol)": "🍸",
    "bar & pub": "🍺", 
    "bagel, shop": "🥯",
    "bakery, shop": "🥖",
    "bookstore, book shop, shop": "📚",
    "breakfast spot": "🥞",
    "burrito, mexican restaurant, mexican food, restaurant": "🌯",
    "cafe, coffee, tea, tea house": "☕",
    "chinese restaurant, chinese food, restaurant": "🍜",
    "coffee, cafe": "☕",
    "college bookstore, shop": "📚",
    "college cafe, cafe, coffee, tea": "☕",
    "diner, restaurant": "🍽️",
    "egyptian": "🥙",
    "gluten free, gluten free restaurant, gluten free food, restaurant": "🥦",
    "greek restaurant, greek food, restaurant": "🥙",
    "french": "🥐",
    "hunan restaurant, hunan food, chinese restaurant, chinese food, restaurant": "🍜",
    "indian restaurant, indian food, restaurant": "🍛",
    "italian restaurant, italian food, restaurant": "🍝",
    "japanese restaurant, japanese food, restaurant": "🍣",
    "mediterranean restaurant, mediterranean food, restaurant": "🥙",
    "mexican restaurant, mexican food, restaurant": "🌮",
    "new american restaurant, new american food, restaurant": "🍔",
    "pizza, pizza parlor, restaurant": "🍕",
    "restaurant, food": "🍽️",
    "seafood, seafood restaurant, restaurant": "🦞",
    "southern soul food": "🍗",
    "spanish restaurant, spanish food, restaurant": "🥘",
    "steakhouse, steak, restaurant": "🥩",
    "sushi restaurant, sushi, japanese restaurant, japanese food, restaurant": "🍣",
    "turkish": "🥙",
    "thai restaurant, thai food, restaurant": "🍜",
    "vegetarian, vegan, vegetarian food, vegan food, vegetarian restaurant, vegan restaurant, restaurant": "🥗",
    "vietnamese restaurant, vietnamese food, restaurant": "🍜",
};